// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5gJI_PyHZuZ5RTjMp0dtpVupqe7cTee0',
    appId: '1:239164685597:web:5e202e0b785f67e77b75f4',
    messagingSenderId: '239164685597',
    projectId: 'testing-cli-ead18',
    authDomain: 'testing-cli-ead18.firebaseapp.com',
    storageBucket: 'testing-cli-ead18.firebasestorage.app',
    measurementId: 'G-XQ1T4P3MBX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5sSqSgUx8HoBTLYvYecPxwKZ3csfNa18',
    appId: '1:239164685597:android:9f1e378750b297f47b75f4',
    messagingSenderId: '239164685597',
    projectId: 'testing-cli-ead18',
    storageBucket: 'testing-cli-ead18.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaRaXDHPuwcB2cWK-nHv8cHE50yeVDcsY',
    appId: '1:239164685597:ios:cbd4eff0ea6f98327b75f4',
    messagingSenderId: '239164685597',
    projectId: 'testing-cli-ead18',
    storageBucket: 'testing-cli-ead18.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaRaXDHPuwcB2cWK-nHv8cHE50yeVDcsY',
    appId: '1:239164685597:ios:cbd4eff0ea6f98327b75f4',
    messagingSenderId: '239164685597',
    projectId: 'testing-cli-ead18',
    storageBucket: 'testing-cli-ead18.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5gJI_PyHZuZ5RTjMp0dtpVupqe7cTee0',
    appId: '1:239164685597:web:e16f2921482957c67b75f4',
    messagingSenderId: '239164685597',
    projectId: 'testing-cli-ead18',
    authDomain: 'testing-cli-ead18.firebaseapp.com',
    storageBucket: 'testing-cli-ead18.firebasestorage.app',
    measurementId: 'G-67BYPFSQ1B',
  );
}
